spring:
  datasource:
    url: jdbc:h2:mem:roombooking;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# JWT settings must match what your JwtTokenProvider expects:
jwt:
  secret: VerySecretKeyForJwtDontShare   # at least 32 characters
  expiration-ms: 3600000                # e.g. 1h in milliseconds

logging:
  level:
    org.hibernate.SQL: DEBUG
    com.example.roombooking: DEBUG
